name: Prepare
description: Prepares the repo for a typical CI job

runs:
  using: composite
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
