name: 'Install'
description: 'Sets up Node, and installs dependencies'

runs:
  using: composite
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
