name: _code-quality

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run ESLint check
        run: |
          rm -rf .turbo/runs
          pnpm exec turbo run lint --affected --summarize

      - name: Summarize Turbo cache
        if: always()
        uses: ./.github/composite-actions/turbo-cache-summary

      - name: Run Prettier check
        run: pnpm run format:check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run type checks
        run: |
          rm -rf .turbo/runs
          pnpm exec turbo run typecheck --affected --summarize

      - name: Summarize Turbo cache
        if: always()
        uses: ./.github/composite-actions/turbo-cache-summary

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run unit tests
        run: |
          rm -rf .turbo/runs
          pnpm exec turbo run test --affected --summarize -- --reporter=default

      - name: Summarize Turbo cache
        if: always()
        uses: ./.github/composite-actions/turbo-cache-summary
