name: main
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: 'ESLint'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: pnpm run lint

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Unit Tests
        run: pnpm run test
